# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages

matrix:
  include:
  - r: release
  - r: devel
  - r: oldrel
  # test with the dev version of ggplot2
  - r: release
    r_github_packages:
    - tidyverse/ggplot2
    - lionel-/vdiffr


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
