# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
  - r: release
  - r: devel
  - r: oldrel
  # test with the dev version of ggplot2
  - r: release
    r_github_packages:
    - tidyverse/ggplot2
    - lionel-/vdiffr
