# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
dist: xenial
sudo: false
cache: packages

matrix:
  fast_finish: true
  include:
  - r: release
  - r: devel
  - r: oldrel
  # test with the dev version of ggplot2
  - r: release
    r_github_packages:
    - tidyverse/ggplot2
    - lionel-/vdiffr


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update --yes --force-yes
  - sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev
