# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  fast_finish: true
  include:
  - r: release
    # TODO: remove this when the new version of ggplot2 will be released
    env: VDIFFR_RUN_TESTS=false
  - r: devel
    env: VDIFFR_RUN_TESTS=false
  - r: oldrel
    env: VDIFFR_RUN_TESTS=false
  # test with the dev version of ggplot2
  - r: release
    r_github_packages:
    - tidyverse/ggplot2

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
